### status
GET http://localhost:5000/status


### Boas vindas
GET http://localhost:5000/contas/1313-0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiMmY3YWYxNDItMDFiZC00NzhkLWIxOWMtN2QzNGIxNzZiMGNkIiwiZW1haWwiOiJmdWxhbm9AZW1haWwuY29tIiwiaWF0IjoxNzA3MTczOTk2LCJleHAiOjE3MDcxNzc1OTZ9.wzKBVnQuZfHE1SG1SrlDTF4fV_bmqd2r4-4K2RCa_C4


### Saldo
GET http://localhost:5000/contas/1313-0/saldo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiMmY3YWYxNDItMDFiZC00NzhkLWIxOWMtN2QzNGIxNzZiMGNkIiwiZW1haWwiOiJmdWxhbm9AZW1haWwuY29tIiwiaWF0IjoxNzA2OTE5NTg1LCJleHAiOjE3MDY5MjMxODV9.8I_RCN2Emi1rx0CrnDpaia_jIM6AxN2XfAMZPELu0Tc


### Depósito DINHEIRO
POST http://localhost:5000/contas/1313-0/deposito
Content-Type: application/json

{
  "valor": 100,
  "tipo_deposito": "DINHEIRO"
}

### Login
POST http://localhost:5000/login
Content-Type: application/json 

{
  "email": "fulano@email.com",
  "senha": "123456"
}


### Login pessoa
POST http://localhost:5000/pessoas/login
Content-Type: application/json 

{
  "usuario": "cezarmezzalira",
  "senha": "123456"
}

### Cadastro pessoa
POST http://localhost:5000/pessoas/cadastrar
Content-Type: application/json  

{
  "nome_completo": "Cezar Augusto Mezzalira",
  "cpf": "12100393",
  "usuario": "cezarmezzalira",
  "senha": "123456"
}

### Atualizar dados pessoa
PATCH http://localhost:5000/pessoas/2c4e1c56-dccd-4cee-ab16-3ab93699445a/atualizar
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXNzb2FfaWQiOiIyYzRlMWM1Ni1kY2NkLTRjZWUtYWIxNi0zYWI5MzY5OTQ0NWEiLCJwcml2aWxlZ2lvIjoic2VtLWFjZXNzbyIsImlhdCI6MTcwNzM1Mzg3MywiZXhwIjoxNzA3MzU3NDczfQ.rcmfjGM4Q-E9nUuZ-deLwJ8sEDuGFj19tqxGPIkVt9U

{
  "nome_completo": "Cezar Mezzalira",
  "cpf": "1234567890",
  "usuario": "cezarmezzalira",
  "senha": "123456"
}