### status
GET http://localhost:5000/status


### Boas vindas
GET http://localhost:5000/contas/1313-0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiMmY3YWYxNDItMDFiZC00NzhkLWIxOWMtN2QzNGIxNzZiMGNkIiwiZW1haWwiOiJmdWxhbm9AZW1haWwuY29tIiwiaWF0IjoxNzA3MTczOTk2LCJleHAiOjE3MDcxNzc1OTZ9.wzKBVnQuZfHE1SG1SrlDTF4fV_bmqd2r4-4K2RCa_C4


### Saldo
GET http://localhost:5000/contas/1313-0/saldo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiMmY3YWYxNDItMDFiZC00NzhkLWIxOWMtN2QzNGIxNzZiMGNkIiwiZW1haWwiOiJmdWxhbm9AZW1haWwuY29tIiwiaWF0IjoxNzA2OTE5NTg1LCJleHAiOjE3MDY5MjMxODV9.8I_RCN2Emi1rx0CrnDpaia_jIM6AxN2XfAMZPELu0Tc


### Depósito DINHEIRO
POST http://localhost:5000/contas/1313-0/deposito
Content-Type: application/json

{
  "valor": 100,
  "tipo_deposito": "DINHEIRO"
}

### Login
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "fulano@email.com",
  "senha": "123456"
}